apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres

resources:
- postgres.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: postgres-initdb
  files:
    - initdb/init-chirpstack.sh
    - initdb/chirpstack_extensions.sh
  options:
    disableNameSuffixHash: true