apiVersion: apps/v1
kind: Deployment
metadata:
  name: chirpstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chirpstack
  template:
    metadata:
      labels:
        app: chirpstack
    spec:
      containers:
        - name: chirpstack
          image: chirpstack/chirpstack:4
          command: ["/bin/sh", "-c", "chirpstack --config /etc/chirpstack"]
          env:
            - name: MQTT_BROKER_HOST
              value: "mosquitto"
            - name: REDIS_HOST
              value: "redis"
            - name: POSTGRESQL_HOST
              value: "postgres"
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "300m"
              memory: "512Mi"
            limits:
              cpu: "600m"
              memory: "1Gi"
          volumeMounts:
            - name: config
              mountPath: /etc/chirpstack
      volumes:
        - name: config
          configMap:
            name: chirpstack-configuration

---
apiVersion: v1
kind: Service
metadata:
  name: chirpstack
spec:
  type: NodePort
  selector:
    app: chirpstack
  ports:
      port: 8080
      targetPort: 8080
      nodePort: 30080