apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: chirpstack

resources:
- chirpstack.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - configuration/chirpstack.toml
  - configuration/region_au915_0.toml
  - configuration/region_au915_1.toml
  name: chirpstack-configuration